name: Azure Acorn And Oak CI/CD

on:
  push:
    branches: 
      - master

env:
  AZURE_WEBAPP_NAME: acorn-and-oak-2
  AZURE_WEBAPP_APTH: '/acorn-and-oak-photography'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_ACORN_AND_OAK_DEPLOY }}

      - name: SETUP
